<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>

<img style="display: inline;" src="<?php echo $this->getViewFileUrl('Vexpro_CompraPontos::img/ico_real.png'); ?>" />
<span>&nbsp;&nbsp;</span>

<?php if ($block->hasSpecialPrice()) :?>
    <span class="special-price" style="font-size: 15px; color: #102972; font-weight: bold;">
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price" style="font-size: 15px; color: #102972; font-weight: bold;">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else :?>
    <span style="font-size: 15px; color: #102972; font-weight: bold;">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>

<div>

<?php
$_product = $block->getPriceType('final_price')->getProduct();
$attvalue = $_product->getCustomAttribute('pontos_produto')->getValue();
if ($attvalue > 0)
{
    ?>
    <img style="display: inline;" src="<?php echo $this->getViewFileUrl('Vexpro_CompraPontos::img/ico_seed.png'); ?>" />
    <span>&nbsp;&nbsp;</span>
    <span class="special-price" style="font-size: 15px; color: #3351A8; font-weight: bold;">
        <?php
        echo ("SD$ ".round($attvalue));
        ?>
    </span>
    <?php
}
?>
<?php
    echo "<p>";
    if (($_product->getCustomAttribute('mostrar_pontuacao')->getValue()) == 1)
    {
        ?>
        <span class="special-price" style="font-size: 15px; color: #3351A8; font-weight: bold;">
            <img style="display: inline;" src="<?php echo $this->getViewFileUrl('Vexpro_PontosProduto::images/pontuara.png'); ?>" />
            <span>&nbsp;&nbsp;</span>
            <?php
            echo "Você pontuará SD$ " . $_product->getCustomAttribute('pontuacao')->getValue();?>
        </span>
        <?php
    }
    echo "</p>";
?>
</div>